### ISSUE TITLE
Concurrent Jobs

### ISSUE THREAD

**Issue by asampley** [CMPUT301W16T15/Shareo#11]
Builders and Deleters have been implemented with Jobs, but there is no way currently to wait for a Building or Deleting to finish.

**Comment by Bradshawz** [comment]
Unless there's a specific needed use case, this doesn't need to be implemented.

**Comment by asampley** [comment]
Are the jobs guaranteed to be executed in the order that they were sent? If so, I will agree, and the problem I am having may be because User does not use a Job yet.

**Comment by Bradshawz** [comment]
They can be made to do so, but currently do not.

**Comment by asampley** [comment]
Upon further inspection, there is a Job for User, but it is implemented differently than all the rest (that I have looked at). Others have the Builders call the Job, but User has the Job call the builder. Should this be the other way around?

**Comment by asampley** [comment]
The main problem that I have with the inability to control the order, is that it makes things very difficult to test.

**Comment by Bradshawz** [comment]
Use main thread for tests. Might not have implemented that in user. Junit is not suitable for testing multithreaded code by itself.

**Comment by asampley** [comment]
Okay, I will implement it if it hasn't been, and resolve this issue when it's done.
