### ISSUE TITLE
When you remove a bid, the bids list doesnt update until you change tab

### ISSUE THREAD

**Issue by 0x4849a** [CMPUT301W16T15/Shareo#15]
I think abradsha fixed that problem in Home Fragment and it's showing up again in the bids.

**Comment by 0x4849a** [comment]
When I was doing the demo and I deleted a bid from the bids tab, the result of the bid no longer showing up in the listview wasnt apparent until I logged out and logged back in.

So declining an offer seems to work and is apparent instantly but deleting a bid is not.

**Comment by Bradshawz** [comment]
Fixed this in the past but it came back due to a separate bug i fixed. Fixed again. For now.
