### ISSUE TITLE
One bid appearing multiple times in Bids list

### ISSUE THREAD

**Issue by 0x4849a** [CMPUT301W16T15/Shareo#16]
Steps to reproduce:
Step1) Create a new user and sign up
Step2) Search for "game" and then bid on sally's game.
Step3) Check the bids tab and you'll see two instances of the same bid.

If you log out and log back in as your new user, it only shows up as one bid.

**Comment by 0x4849a** [comment]
The only way this bug doesnt appear is if you either 
-  A) bid on multiple items at one time before going to the bids tab
- B) I think if you are not a new account you won't get it?, so you have logged in and logged out before.

Video of bug is here(I was trying to do the demo).
https://www.youtube.com/watch?v=CuQ_0SAX42Q&feature=youtu.be

Bug is around 3:05

**Comment by Bradshawz** [comment]
Bids would add an id to bid ids and then get the bids, followed by adding the bid manually to the list causing duplicates. Fixed.
