### ISSUE TITLE
Add a Game Problems

### ISSUE THREAD

**Issue by 0x4849a** [CMPUT301W16T15/Shareo#6]
When you hit save in add a game, it doesn't show up in the HomeFragment until you log back in usually(sometimes back works).
 Also, for some reason there's like multiple instances of one game being shown each time you add one.

**Comment by Bradshawz** [comment]
The UI isnt really hooked up at all. The reason it never appears is because the list its displaying a derrived list from the original list, and thats never updates. I havnt had duplicate problems and thats a pretty big deal. What username is the data under that you experianced duplicates?

**Comment by Bradshawz** [comment]
nvm just recreated it

**Comment by Bradshawz** [comment]
Accidentally left in code i used to try to circumvent issues in the tests, let me know if the duplicate problem is fixed. Also as long as you dont switch tabs, it should update with new games.
