### ISSUE TITLE
Edit Profile characters

### ISSUE THREAD

**Issue by 0x4849a** [CMPUT301W16T15/Shareo#8]
If you add a bunch of quotations or non-standard character to Edit Profile's textfields, it crashes.
This also happened to me in the lab environment when I was making a profile from the login screen but I havent been able to reproduce that.

**Comment by asampley** [comment]
We need to sanitize some of our fields, like for username, we should restrict it to alpha-numeric, and for other fields, alpha-numeric with spaces and maybe a few symbols (like email addresses).

**Comment by 0x4849a** [comment]
Cant reproduce so closed for now lol
